---
name: terraform - Import Initiatives

on:  # yamllint disable-line rule:truthy
  push:
    branches:
     # - main
     # - onboarding
      - none
    paths:
      - .github/workflows/terraform-import-initiatives.yml
      - terraform/modules/policy_initiatives/**
      - terraform/scripts/import-initiatives.ps1
      - modules/policies/initiatives/**
  pull_request:
    types:
      - opened
    branches:
      # - main
      - none
    paths:
      - .github/workflows/terraform-import-initiatives.yml
      - terraform/modules/policy_initiatives/**
      - terraform/scripts/import-initiatives.ps1
      - modules/policies/initiatives/**
  workflow_dispatch:

# Checks if any concurrent jobs under the same pull request or branch are being executed - prevents the terraform state file being locked by another running workflow
concurrency:
  group: ${{ github.head_ref || github.ref_name }}

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: policy-initiatives
  LOCATION: westeurope

jobs:
  import_canary:
    name: Terraform import Canary initiatives
    environment:
      name: Canary
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: canary
      PREFIX: matthew-lz-canary
      tf_actions_working_dir: ./terraform/modules/policy_initiatives/canary
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.38.1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }} -backend-config=container_name=${{ secrets.CONTAINER_NAME }} -backend-config=key=${{ secrets.KEY }} -backend-config=resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      # create a terraform workspace to manage state for this module if it does not exist. Workspaces separate state within the same state file for different modules
      - name: Terraform Workspace create
        id: tf_workspace_create
        run: terraform workspace new ${{ env.MODULE_NAME }} || echo "Workspace ${{ env.MODULE_NAME }}  already exists or cannot be created"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      # workspace variable needs to be set after the workspace is created
      - name: Terraform Workspace export
        id: tf_workspace_export
        run: export TF_WORKSPACE=${{ env.MODULE_NAME }}

      # select the terraform workspace
      - name: Terraform Workspace select
        id: tf_workspace_select
        run: terraform workspace select ${{ env.MODULE_NAME }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Terraform Import Resources
        id: import-terraform-resources
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/terraform/scripts/import-initiatives.ps1 -importDir "terraform/modules/policy_initiatives/canary" -policyDir "../../../../modules/policies/initiatives"  -mgmtGroupName ${{ env.PREFIX }} -storageAccountName ${{ secrets.STORAGE_ACCOUNT_NAME }} -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -containerName ${{ secrets.CONTAINER_NAME }} -tfStateFile ${{ secrets.KEY }} -ARM_CLIENT_ID ${{ secrets.AZURE_CLIENT_ID }} -ARM_SUBSCRIPTION_ID ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }} -ARM_TENANT_ID ${{ secrets.AZURE_TENANT_ID }}
          azPSVersion: latest

      - name: Terraform Plan
        id: plan
        run: terraform plan --out=out_canary.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Upload the plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan-canary
          path: ${{ env.tf_actions_working_dir }}/out_canary.tfplan

  import_prod:
    name: Terraform import Production initiatives
    environment:
      name: Production
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: prod
      PREFIX: matthew-lz
      tf_actions_working_dir: ./terraform/modules/policy_initiatives/prod
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.38.1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }} -backend-config=container_name=${{ secrets.CONTAINER_NAME }} -backend-config=key=${{ secrets.KEY }} -backend-config=resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      # create a terraform workspace to manage state for this module if it does not exist. Workspaces separate state within the same state file for different modules
      - name: Terraform Workspace create
        id: tf_workspace_create
        run: terraform workspace new ${{ env.MODULE_NAME }} || echo "Workspace ${{ env.MODULE_NAME }}  already exists or cannot be created"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      # workspace variable needs to be set after the workspace is created
      - name: Terraform Workspace export
        id: tf_workspace_export
        run: export TF_WORKSPACE=${{ env.MODULE_NAME }}

      # select the terraform workspace
      - name: Terraform Workspace select
        id: tf_workspace_select
        run: terraform workspace select ${{ env.MODULE_NAME }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Terraform Import Resources
        id: import-terraform-resources
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/terraform/scripts/import-initiatives.ps1 -importDir "terraform/modules/policy_initiatives/prod" -policyDir "../../../../modules/policies/initiatives"  -mgmtGroupName ${{ env.PREFIX }} -storageAccountName ${{ secrets.STORAGE_ACCOUNT_NAME }} -ResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME }} -containerName ${{ secrets.CONTAINER_NAME }} -tfStateFile ${{ secrets.KEY }} -ARM_CLIENT_ID ${{ secrets.AZURE_CLIENT_ID }} -ARM_SUBSCRIPTION_ID ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }} -ARM_TENANT_ID ${{ secrets.AZURE_TENANT_ID }}
          azPSVersion: latest

      - name: Terraform Plan
        id: plan
        run: terraform plan --out=out_prod.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Upload the plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan-prod
          path: ${{ env.tf_actions_working_dir }}/out_prod.tfplan
